# Generated by Django 5.2.4 on 2025-07-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("date", models.DateField(auto_now_add=True)),
                ("location", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("parity", models.IntegerField()),
                (
                    "menopausal_status",
                    models.CharField(
                        choices=[("Pre", "Pre"), ("Post", "Post")], max_length=10
                    ),
                ),
                ("vaginal_delivery", models.BooleanField()),
                ("c_section", models.BooleanField()),
                (
                    "physical_activity",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Moderate", "Moderate"),
                            ("High", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "diet_fibre",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Adequate", "Adequate"),
                            ("High", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                ("fluid_intake", models.FloatField()),
                (
                    "travel_frequency",
                    models.CharField(
                        choices=[
                            ("None", "None"),
                            ("Occasional", "Occasional"),
                            ("Frequent", "Frequent"),
                        ],
                        max_length=15,
                    ),
                ),
                ("sleep_hours", models.FloatField()),
                (
                    "stress_level",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Moderate", "Moderate"),
                            ("High", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                ("withholding_behavior", models.BooleanField()),
                ("self_perceived_constipation", models.BooleanField()),
                ("rome_iv_constipation", models.BooleanField()),
                ("group_label", models.CharField(max_length=50)),
            ],
        ),
    ]
