# Generated by Django 5.2.4 on 2025-07-07 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("radio", "Single Choice"),
                            ("checkbox", "Multiple Choice"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="participant",
            name="diet_fibre",
        ),
        migrations.RemoveField(
            model_name="participant",
            name="fluid_intake",
        ),
        migrations.RemoveField(
            model_name="participant",
            name="physical_activity",
        ),
        migrations.RemoveField(
            model_name="participant",
            name="rome_iv_constipation",
        ),
        migrations.RemoveField(
            model_name="participant",
            name="self_perceived_constipation",
        ),
        migrations.RemoveField(
            model_name="participant",
            name="sleep_hours",
        ),
        migrations.RemoveField(
            model_name="participant",
            name="stress_level",
        ),
        migrations.RemoveField(
            model_name="participant",
            name="travel_frequency",
        ),
        migrations.RemoveField(
            model_name="participant",
            name="withholding_behavior",
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="questionnaire.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="questionnaire.participant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.TextField(blank=True, null=True)),
                (
                    "choice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="questionnaire.choice",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questionnaire.question",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="questionnaire.response",
                    ),
                ),
            ],
        ),
    ]
