# Generated by Django 5.2.4 on 2025-07-08 09:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0002_question_remove_participant_diet_fibre_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessorRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("reason", models.TextField()),
                ("token", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("approved", models.BooleanField(default=False)),
                ("declined", models.BooleanField(default=False)),
            ],
        ),
    ]
