# Generated by Django 5.2.4 on 2025-07-08 10:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0003_assessorrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessorrequest",
            name="token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="participant",
            name="menopausal_status",
            field=models.CharField(
                choices=[("Pre", "Pre-menopausal"), ("Post", "Post-menopausal")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("radio", "Single Choice"),
                    ("checkbox", "Multiple Choice"),
                ],
                max_length=20,
            ),
        ),
    ]
