# Generated by Django 5.2.4 on 2025-07-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0004_alter_assessorrequest_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessorrequest",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
