# Generated by Django 5.2.4 on 2025-07-10 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0006_survey"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="survey",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="questionnaire.survey",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("date", "Date"),
                    ("number", "Number"),
                    ("radio", "Single Choice"),
                    ("checkbox", "Multiple Choice"),
                ],
                max_length=20,
            ),
        ),
    ]
