# Generated by Django 5.2.4 on 2025-07-11 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0008_rename_group_label_participant_contact_info_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="questionnaire.survey",
            ),
        ),
    ]
