# Generated by Django 5.2.4 on 2025-07-12 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0010_question_question_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="survey",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="questionnaire.survey",
            ),
            preserve_default=False,
        ),
    ]
